---
- name: Companion to the pipeline for easier setup
  hosts: all
  become: true
  gather_facts: false

  tasks:
  # newer ansible doesn't work with python3.6, which is the system python on rhel8
    - name: Check OS release version
      ansible.builtin.raw: cat /etc/redhat-release
      register: release_out
      changed_when: false
    - name: Install Python 3.9 on RHEL/CentOS 8 systems
      ansible.builtin.raw: |
        dnf -y module enable python39
        dnf -y install python39
      args:
        executable: /bin/bash
      when: |
        'Red Hat Enterprise Linux release 8.' in release_out.stdout
        or 'CentOS Linux release 8' in release_out.stdout
        or 'CentOS Stream release 8' in release_out.stdout
      changed_when: false
    - name: Install required packages
      # avoid dnf module (missing for rhel-8, not really necessary elsewhere)
      ansible.builtin.raw: |
        dnf -y install python3 podman-docker podman
      args:
        executable: /bin/bash  
    - name: Suppress podman-docker message
      ansible.builtin.file:
        path: /etc/containers/nodocker
        state: touch
    - name: Add auth_file, pull the image and tag it
      block:
        - ansible.builtin.tempfile:
            state: file
            prefix: auth_file_
            path: /var/tmp
          register: auth_file
        - ansible.builtin.copy:
            dest: "{{ auth_file.path }}"
            content: "{{ AUTHFILE_b64 | b64decode }}"
        - ansible.builtin.lineinfile:
            path: "{{TMT_PLAN_ENVIRONMENT_FILE}}"
            create: yes
            line: "REGISTRY_AUTH_FILE={{auth_file.path}}"
          when: TMT_PLAN_ENVIRONMENT_FILE | length > 0
        - ansible.builtin.command:
            argv:
              - podman
              - pull
              - --authfile
              - "{{ auth_file.path }}"
              - "{{ IMAGE_URL }}"
          when: IMAGE_URL | length > 0
        - ansible.builtin.command:
            argv:
              - podman
              - tag
              - "{{ IMAGE_URL }}"
              - "{{ IMAGE_NAME }}"
      when: AUTHFILE_b64 | length > 0
